# Generated by Django 4.2.1 on 2023-05-16 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0003_rename_name_menu_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='special',
            field=models.BooleanField(default=False),
        ),
    ]
