# Generated by Django 4.2.1 on 2023-05-16 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0004_menu_special'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='special_image',
            field=models.ImageField(blank=True, null=True, upload_to='menu/'),
        ),
    ]
